### ISSUE TITLE
Button Handler missing at final round

### ISSUE THREAD

**Issue by maze233** [maze233/StoeppliApp#18]
If there is a player in the final round with play mode „taptostop“ enabled, the second player cannot use the Go button

**Comment by crzdg** [comment]
fixed
after a players stops targets of button gets removed in any case. button doesn't have a target before the delay. after the delay, the target .touchUpInside is set as every player is using this type to start the game. (compare to gameButton disable)

as soon this target gets triggered (so player starts run), the target get removed again, and afterwards set through a UI method which determines the playmode of the player and sets a target for it.
